### ISSUE TITLE
Bing cognitive search service search string

### ISSUE THREAD

**Issue by GreenEyedAndy** [ProfessionalCSharp/ProfessionalCSharp6#26]
Hi Christian,
I tried you async example, but it seems it's not working.
After a quick research I found that the Bing Url has changed:
$top -> $count
$skip -> $offset

https://api.cognitive.microsoft.com/bing/v5.0/images/search?q={SearchTerm}&$count={Count}&$offset={Offset}

Can you verify this?

**Comment by christiannagel** [comment]
Hi Andy,
Thank you for opening this issue @GreenEyedAndy  
You're correct, the Bing Url has changed. I missed changing the query parameters from the previous version of the sample. It was not throwing an exception, but not returning the correct number of items.
It's now
$top -> count
$skip -> offset
(removed $ from your snippet)

[Upgrading from Bing API Version 2 to Version 5](https://msdn.microsoft.com/en-US/library/mt707570.aspx#image) shows the old and new options for image search.

Thanks again.
