### ISSUE TITLE
Debug target does not exist

### ISSUE THREAD

**Issue by MarcLongoria** [ProfessionalCSharp/ProfessionalCSharp6#30]
In the Inheritance solution under both the VirtualMethods and InheritanceWithConstructors projects, an error appears when trying to debug:

![csharperror](https://cloud.githubusercontent.com/assets/2634699/21585165/9d55d5a8-d080-11e6-8eff-90345c47a719.JPG)

The error appears to originate in the launchSettings.json file due possibly to the sdkVersion used in the program. 1.0.0-rc2 is not installed on my machine though 1.0.1 is. Perhaps updating this to the version on the machine will remove the error but removing the launchSetting.json entirely from the project worked for me though they may be a better answer. The UsingInterfaces project in the same solution does not have said json file and works fine.

**Comment by christiannagel** [comment]
Thanks @ToMissTheMarc. As you mentioned, the issue is because of different SDK versions in launchSettings.json. I removed these files.
Also, I added global.json which resolves an issue if Visual Studio 2017 RC is installed on the same system.

**Comment by MarcLongoria** [comment]
Sounds great! Thank you very much. There was next to no documentation about this issue on the web (yet) so it was hard to find the reason at first.

**Comment by christiannagel** [comment]
blogged about versioning issues, including VS2017 and VS2015 - see: https://csharp.christiannagel.com/2017/01/10/dotnetcoreversionissues/
