### ISSUE TITLE
Chapter 45: no web.config in .NET Framework projects

### ISSUE THREAD

**Issue by nicowitteman** [ProfessionalCSharp/ProfessionalCSharp6#40]
I believe VS (using VS Community 2017) and/or frameworks have changed since you wrote chapter 45 (p. 1405): new ASP.NET projects no longer include config.web. Aso, the source files for this chapter distributed from wrox or github do not include web.config.
You might want to add corrections to https://github.com/ProfessionalCSharp/ProfessionalCSharp6/blob/master/BookUpdates.md

**Comment by christiannagel** [comment]
Thanks for the information. The issue was a different one:
Page 1405 describes deployment of an ASP.NET 4.6 project, and the updated source code I had in this chapter was ASP.NET Core with the .NET Framework. Updated the source code accordingly.
